export interface Service {
  slug: string;
  category: string;
  categorySlug: string;
  name: string;
  tagline: string;
  description: string;
  startingPrice: string;
  deliveryTime: string;
  icon: string;
  features: string[];
  process: { step: string; detail: string }[];
  faqs: { q: string; a: string }[];
}

export const services: Service[] = [
  // ─── WEB DEVELOPMENT ────────────────────────────────────────────────────
  {
    slug: "shopify-store",
    category: "Web Development",
    categorySlug: "web-development",
    name: "Shopify Store Development",
    tagline: "Custom Shopify stores built to sell",
    description:
      "We design and build high-converting Shopify stores tailored to your brand. From theme customisation to custom apps, product setup, and payment integration — we handle everything so you can start selling fast.",
    startingPrice: "Price on request",
    deliveryTime: "7–14 days",
    icon: "ShoppingBag",
    features: [
      "Custom theme design or premium theme setup",
      "Product catalogue setup (up to 50 products)",
      "Payment gateway integration (Stripe, PayPal, COD)",
      "Mobile-first responsive design",
      "SEO-optimised product pages",
      "WhatsApp chat integration",
      "Google Analytics + Meta Pixel setup",
      "30 days post-launch support",
    ],
    process: [
      { step: "Discovery", detail: "We understand your products, brand, and target customers" },
      { step: "Design", detail: "Wireframes and theme selection or custom design mockup" },
      { step: "Development", detail: "Build, configure apps, set up products and payments" },
      { step: "Review", detail: "You test the store and request any changes" },
      { step: "Launch", detail: "Go live — we handle DNS and final checks" },
    ],
    faqs: [
      { q: "Do I need a Shopify subscription?", a: "Yes, Shopify starts at $39/month. We help you choose the right plan." },
      { q: "Can you migrate my existing store?", a: "Yes, we migrate products, customers, and orders from WooCommerce, Wix, or other platforms." },
      { q: "Do you add custom features?", a: "Yes — custom sections, apps, and integrations are available as add-ons." },
    ],
  },
  {
    slug: "woocommerce-store",
    category: "Web Development",
    categorySlug: "web-development",
    name: "WooCommerce Development",
    tagline: "Powerful ecommerce on WordPress — you own it completely",
    description:
      "We build custom WooCommerce stores on WordPress — the world's most flexible ecommerce platform. No monthly platform fees, full control over your data, and unlimited customisation.",
    startingPrice: "Price on request",
    deliveryTime: "7–14 days",
    icon: "Store",
    features: [
      "Custom WordPress + WooCommerce setup",
      "Theme design or premium theme configuration",
      "Payment gateway: Stripe, PayPal, bank transfer",
      "Product setup (up to 50 SKUs)",
      "Shipping and tax configuration",
      "SEO plugin setup (Yoast or Rank Math)",
      "Security hardening + SSL",
      "30 days post-launch support",
    ],
    process: [
      { step: "Discovery", detail: "Brand, products, and feature requirements" },
      { step: "Design", detail: "Theme selection and design customisation" },
      { step: "Development", detail: "Plugin setup, products, payments, shipping" },
      { step: "Review", detail: "Full walkthrough with you before launch" },
      { step: "Launch", detail: "Deploy to your hosting, DNS, final QA" },
    ],
    faqs: [
      { q: "WooCommerce vs Shopify — which is better?", a: "WooCommerce gives you more control and lower running costs. Shopify is easier to manage long-term. We can advise based on your needs." },
      { q: "Do I need hosting?", a: "Yes — we recommend our hosting plans or can set up on any host you prefer." },
    ],
  },
  {
    slug: "company-website",
    category: "Web Development",
    categorySlug: "web-development",
    name: "Company Website Development",
    tagline: "Professional websites that build trust and generate leads",
    description:
      "We build fast, modern company websites — from simple 5-page brochure sites to complex multi-department portals. Every site is mobile-first, SEO-ready, and designed to convert visitors into customers.",
    startingPrice: "Price on request",
    deliveryTime: "5–10 days",
    icon: "Globe",
    features: [
      "Up to 8 pages (Home, About, Services, Contact, etc.)",
      "Mobile-first responsive design",
      "Contact form with email notifications",
      "Google Maps integration",
      "WhatsApp chat button",
      "Basic on-page SEO",
      "Google Analytics setup",
      "Fast hosting-ready export or deployment",
    ],
    process: [
      { step: "Brief", detail: "Collect your content, brand colours, and logo" },
      { step: "Design", detail: "Homepage mockup for approval before building" },
      { step: "Build", detail: "Develop all pages with your content" },
      { step: "Review", detail: "2 rounds of revisions included" },
      { step: "Launch", detail: "Deploy and handover" },
    ],
    faqs: [
      { q: "Do I need to provide content?", a: "We can write basic content for you as an add-on, or you can provide text and images." },
      { q: "Can I update the site myself?", a: "Yes — we can build on WordPress so you can edit content easily, or on Next.js for better performance." },
    ],
  },

  // ─── DIGITAL MARKETING ────────────────────────────────────────────────────
  {
    slug: "google-ads",
    category: "Digital Marketing",
    categorySlug: "digital-marketing",
    name: "Google Ads Management",
    tagline: "Get found by customers who are actively searching",
    description:
      "We set up and manage Google Search, Display, Shopping, and Performance Max campaigns that bring you qualified leads. Full keyword research, ad copywriting, landing page review, and monthly reporting included.",
    startingPrice: "Price on request",
    deliveryTime: "Setup in 3–5 days",
    icon: "Search",
    features: [
      "Campaign strategy and keyword research",
      "Ad copywriting (A/B tested)",
      "Audience and bidding configuration",
      "Conversion tracking setup",
      "Google Analytics 4 integration",
      "Monthly performance report",
      "Ongoing optimisation (weekly bid adjustments)",
      "Remarketing campaign setup",
    ],
    process: [
      { step: "Audit", detail: "Review your business, competitors, and current presence" },
      { step: "Strategy", detail: "Define campaigns, keywords, and budgets" },
      { step: "Setup", detail: "Build campaigns, write ads, configure tracking" },
      { step: "Launch", detail: "Go live, monitor closely for the first 72 hours" },
      { step: "Optimise", detail: "Weekly and monthly optimisation cycles" },
    ],
    faqs: [
      { q: "Is the ad spend included?", a: "No — ad spend goes directly to Google. Our fee is for management only." },
      { q: "What's the minimum ad budget?", a: "We recommend at least $500/month in ad spend for meaningful results." },
      { q: "How long until I see results?", a: "Usually within 2–4 weeks of launch." },
    ],
  },
  {
    slug: "meta-ads",
    category: "Digital Marketing",
    categorySlug: "digital-marketing",
    name: "Meta Ads (Facebook + Instagram)",
    tagline: "Reach your audience where they scroll",
    description:
      "We create and manage high-performing Facebook and Instagram ad campaigns. From awareness to conversions — we handle creative strategy, audience targeting, pixel setup, and ongoing optimisation.",
    startingPrice: "Price on request",
    deliveryTime: "Setup in 3–5 days",
    icon: "Megaphone",
    features: [
      "Facebook + Instagram campaign setup",
      "Audience research and targeting",
      "Ad creative strategy and copywriting",
      "Meta Pixel and Conversion API setup",
      "Retargeting and lookalike audiences",
      "A/B testing of creatives and audiences",
      "Monthly performance report",
      "Catalogue / dynamic product ads (ecommerce)",
    ],
    process: [
      { step: "Strategy", detail: "Audience research, competitor analysis, campaign plan" },
      { step: "Creative brief", detail: "Ad formats, copy angles, and image/video guidance" },
      { step: "Setup", detail: "Build campaigns in Ads Manager, configure pixel" },
      { step: "Launch", detail: "Go live, monitor for first 48 hours" },
      { step: "Optimise", detail: "Ongoing weekly optimisation and monthly report" },
    ],
    faqs: [
      { q: "Do you make the ad creatives?", a: "We write copy and provide creative direction. Video/image production is an add-on." },
      { q: "Is ad spend included?", a: "No — ad spend goes directly to Meta. Our fee is management only." },
    ],
  },
  {
    slug: "tiktok-linkedin-ads",
    category: "Digital Marketing",
    categorySlug: "digital-marketing",
    name: "TikTok + LinkedIn Ads",
    tagline: "TikTok for reach, LinkedIn for B2B — we run both",
    description:
      "TikTok Ads for brand awareness and younger audiences. LinkedIn Ads for B2B targeting — decision makers, industries, job titles. We manage both platforms with platform-specific creative strategies.",
    startingPrice: "Price on request",
    deliveryTime: "Setup in 4–6 days",
    icon: "Video",
    features: [
      "TikTok In-Feed and TopView campaigns",
      "LinkedIn Sponsored Content and Message Ads",
      "Platform-specific audience targeting",
      "Ad copywriting and creative direction",
      "TikTok Pixel / LinkedIn Insight Tag setup",
      "Monthly performance reports",
    ],
    process: [
      { step: "Platform selection", detail: "TikTok, LinkedIn, or both based on your goals" },
      { step: "Strategy", detail: "Audience targeting, ad formats, creative approach" },
      { step: "Setup", detail: "Campaign build, tracking, creatives" },
      { step: "Launch + monitor", detail: "Live monitoring for first week" },
      { step: "Monthly optimise", detail: "Regular reporting and adjustments" },
    ],
    faqs: [
      { q: "Is TikTok good for my business?", a: "Absolutely — TikTok has massive global reach, especially for F&B, fashion, lifestyle, and product brands." },
      { q: "What about LinkedIn for small businesses?", a: "LinkedIn works best for B2B, professional services, and HR/recruitment campaigns." },
    ],
  },
  {
    slug: "seo",
    category: "Digital Marketing",
    categorySlug: "digital-marketing",
    name: "SEO Services",
    tagline: "Rank higher on Google — organically",
    description:
      "We provide complete SEO services: technical audit, on-page optimisation, content strategy, and link building. Whether you're starting from scratch or looking to improve rankings, we create a strategy that grows your organic traffic over time.",
    startingPrice: "Price on request",
    deliveryTime: "First report in 7 days",
    icon: "TrendingUp",
    features: [
      "Full technical SEO audit",
      "Keyword research and strategy",
      "On-page optimisation (titles, meta, headers, content)",
      "Schema markup implementation",
      "Google Search Console + Analytics setup",
      "Monthly blog content (optional add-on)",
      "Link building outreach",
      "Monthly ranking report",
    ],
    process: [
      { step: "Audit", detail: "Crawl site, identify technical issues and opportunities" },
      { step: "Strategy", detail: "Keyword map, content gaps, competitor analysis" },
      { step: "On-page", detail: "Fix technical issues, optimise existing pages" },
      { step: "Off-page", detail: "Link building and local citations" },
      { step: "Report", detail: "Monthly ranking and traffic report" },
    ],
    faqs: [
      { q: "How long does SEO take?", a: "You'll start seeing results in 3–6 months. SEO is a long-term investment." },
      { q: "Do you write blog content?", a: "Yes, as an add-on — 2 or 4 posts per month, fully SEO-optimised." },
    ],
  },

  // ─── SMART BUSINESS TOOLS ────────────────────────────────────────────────
  {
    slug: "google-review-card",
    category: "Smart Tools",
    categorySlug: "smart-tools",
    name: "Google Review NFC Card",
    tagline: "One tap — your customer leaves a 5-star review",
    description:
      "A custom-branded NFC card that your customers tap with their phone to instantly open your Google review page. No app needed. Increase your Google reviews effortlessly and build social proof.",
    startingPrice: "Price on request",
    deliveryTime: "3–5 days delivery",
    icon: "Star",
    features: [
      "Custom NFC card with your logo and branding",
      "Tap to open Google review link instantly",
      "Works with all modern smartphones (iPhone + Android)",
      "Durable PVC card (credit-card size)",
      "QR code on reverse side as backup",
      "Optional desk stand version available",
    ],
    process: [
      { step: "Order", detail: "Fill the order form with your business name and Google link" },
      { step: "Design", detail: "We design the card layout with your branding" },
      { step: "Approve", detail: "You approve the design before printing" },
      { step: "Deliver", detail: "Card shipped or collected within 3–5 days" },
    ],
    faqs: [
      { q: "Do I need a Google Business Profile?", a: "Yes — you need a verified Google Business Profile. We can help you set one up." },
      { q: "Can I order multiple cards?", a: "Yes — bulk pricing available for 5+ cards." },
    ],
  },
  {
    slug: "qr-code",
    category: "Smart Tools",
    categorySlug: "smart-tools",
    name: "Custom QR Code",
    tagline: "Branded QR codes for menus, links, payments, and more",
    description:
      "We design custom branded QR codes for any purpose — restaurant menus, product pages, payment links, social media profiles, review pages, or any URL. Delivered as high-resolution files ready for print or digital use.",
    startingPrice: "Price on request",
    deliveryTime: "1–2 days",
    icon: "QrCode",
    features: [
      "Custom branded QR code (your colours + logo in centre)",
      "Links to any URL, PDF, WhatsApp, payment, or social profile",
      "High-resolution files: PNG, SVG, PDF",
      "Print-ready (up to A0 size without quality loss)",
      "Dynamic QR (can update destination URL without reprinting) — add-on",
      "Unlimited scans",
    ],
    process: [
      { step: "Order", detail: "Provide your URL and brand assets (logo, colours)" },
      { step: "Design", detail: "We create the branded QR code" },
      { step: "Deliver", detail: "Files sent via email within 24 hours" },
    ],
    faqs: [
      { q: "What's a dynamic QR code?", a: "A dynamic QR lets you change the destination URL any time without redesigning or reprinting the code." },
      { q: "Can I get a QR for WhatsApp?", a: "Yes — we can create a WhatsApp QR that opens a pre-filled chat with your number." },
    ],
  },
  {
    slug: "digital-business-card",
    category: "Smart Tools",
    categorySlug: "smart-tools",
    name: "Digital Business Card",
    tagline: "Share your contact with one tap — no paper needed",
    description:
      "A professional digital business card hosted on a custom URL or NFC card. Share your name, phone, email, social links, and website with anyone — they tap your card or scan a QR and save your contact instantly.",
    startingPrice: "Price on request",
    deliveryTime: "2–3 days",
    icon: "CreditCard",
    features: [
      "Professionally designed digital profile page",
      "Tap-to-save contact (vCard download)",
      "Links: phone, email, WhatsApp, Instagram, LinkedIn, website",
      "Custom URL (e.g. munzeer.com/card/yourname)",
      "QR code included",
      "NFC card version available as add-on",
      "Analytics: see how many people viewed your card",
    ],
    process: [
      { step: "Order", detail: "Submit your details and brand preferences" },
      { step: "Design", detail: "We design your digital card page" },
      { step: "Review", detail: "You approve before going live" },
      { step: "Share", detail: "You get your link, QR, and optional NFC card" },
    ],
    faqs: [
      { q: "Can I update my card later?", a: "Yes — contact us and we'll update your information at no extra charge." },
      { q: "Does it need an app?", a: "No — it works in any browser. Recipients just click the link." },
    ],
  },
  {
    slug: "3d-business-card",
    category: "Smart Tools",
    categorySlug: "smart-tools",
    name: "3D Business Card Design",
    tagline: "A business card people actually keep",
    description:
      "We design premium 3D-effect business cards that stand out from the pile. Bold design, special finishes (spot UV, embossing, foil), and a first impression that lasts. Delivered as print-ready files — print locally or we source printing for you.",
    startingPrice: "Price on request",
    deliveryTime: "3–5 days (design only)",
    icon: "Layers",
    features: [
      "Double-sided premium business card design",
      "3D / embossed effect design elements",
      "Print-ready files (CMYK, 300dpi, bleed included)",
      "Multiple design concepts to choose from",
      "Spot UV, foil, or embossed finish recommendations",
      "Optional: printing + delivery coordination",
    ],
    process: [
      { step: "Brief", detail: "Your industry, style preferences, and brand assets" },
      { step: "Concepts", detail: "2–3 design concepts presented" },
      { step: "Revise", detail: "Refine chosen concept with 2 revision rounds" },
      { step: "Deliver", detail: "Print-ready files + source files" },
    ],
    faqs: [
      { q: "Can you arrange printing?", a: "Yes — we work with print partners and can coordinate delivery anywhere." },
      { q: "What format do I get?", a: "AI, PDF, and PNG — ready for any printer worldwide." },
    ],
  },
  {
    slug: "ai-chatbot",
    category: "Smart Tools",
    categorySlug: "smart-tools",
    name: "AI Chatbot",
    tagline: "A smart assistant that works 24/7 on your website",
    description:
      "We build and deploy a custom AI chatbot trained on your business information — FAQs, products, services, pricing. It handles customer queries, qualifies leads, and hands off to you on WhatsApp or email when needed.",
    startingPrice: "Price on request",
    deliveryTime: "5–7 days",
    icon: "MessageSquare",
    features: [
      "Trained on your business data (website, PDFs, FAQs)",
      "Embed on your website with one line of code",
      "Handles FAQs, product queries, and lead capture",
      "WhatsApp or email handoff for complex queries",
      "Multi-language support (Arabic + English)",
      "Chat history and analytics dashboard",
      "Monthly conversation reports",
    ],
    process: [
      { step: "Data collection", detail: "Gather your FAQs, product info, and brand voice" },
      { step: "Training", detail: "We train the AI on your business content" },
      { step: "Integration", detail: "Embed on your website and connect to WhatsApp/email" },
      { step: "Test", detail: "Full testing and refinement with you" },
      { step: "Launch", detail: "Go live — we monitor for the first week" },
    ],
    faqs: [
      { q: "Does it speak Arabic?", a: "Yes — our chatbots support Arabic and English natively." },
      { q: "What if the bot can't answer something?", a: "It escalates to you via WhatsApp or email automatically." },
    ],
  },

  // ─── MARKETPLACE LISTINGS ─────────────────────────────────────────────────
  {
    slug: "amazon-listing",
    category: "Marketplace Listings",
    categorySlug: "marketplace-listings",
    name: "Amazon Listing Optimisation",
    tagline: "Get found, get clicks, get sales on Amazon",
    description:
      "We create and optimise Amazon product listings that rank higher and convert better. From keyword research to A+ content, we handle the full listing — title, bullet points, description, backend keywords, and images guidance.",
    startingPrice: "Price on request",
    deliveryTime: "3–5 days per listing",
    icon: "Package",
    features: [
      "Amazon keyword research (high-volume, relevant)",
      "SEO-optimised title (within character limits)",
      "5 benefit-focused bullet points",
      "Enhanced product description",
      "Backend keyword optimisation",
      "A+ Content design (Brand Registered sellers)",
      "Competitor analysis",
      "Image sequence and alt-text recommendations",
    ],
    process: [
      { step: "Brief", detail: "Product details, target market, and competitor ASINs" },
      { step: "Research", detail: "Keyword research and competitor analysis" },
      { step: "Write", detail: "Title, bullets, description, backend keywords" },
      { step: "Review", detail: "You approve before uploading" },
      { step: "Deliver", detail: "Ready-to-upload listing copy + A+ content" },
    ],
    faqs: [
      { q: "Which Amazon marketplaces?", a: "All global Amazon marketplaces — .com, .ae, .sa, .co.uk, .de, and more." },
      { q: "Do you do FBA setup?", a: "We help with listing optimisation. FBA setup guidance is available as a consultation add-on." },
    ],
  },
  {
    slug: "noon-listing",
    category: "Marketplace Listings",
    categorySlug: "marketplace-listings",
    name: "Noon Listing Optimisation",
    tagline: "Dominate the biggest marketplaces in the Middle East",
    description:
      "Noon is the #1 e-commerce marketplace in the Middle East. We create and optimise your Noon product listings for maximum visibility and sales — keyword-rich titles, compelling descriptions, and category-specific optimisation.",
    startingPrice: "Price on request",
    deliveryTime: "3–5 days per listing",
    icon: "ShoppingCart",
    features: [
      "Noon-specific keyword research",
      "Optimised product title and description",
      "Category and attribute configuration",
      "Image upload and sequence guidance",
      "Noon seller account setup guidance (if needed)",
      "Arabic + English listing versions",
    ],
    process: [
      { step: "Brief", detail: "Product info, category, and target customer" },
      { step: "Research", detail: "Noon-specific keyword and category research" },
      { step: "Write", detail: "Full listing copy in English (and Arabic on request)" },
      { step: "Deliver", detail: "Ready-to-upload content package" },
    ],
    faqs: [
      { q: "Do you offer Arabic listings?", a: "Yes — Arabic listing copy is available as an add-on." },
      { q: "Can you help me get a Noon seller account?", a: "Yes — we can guide you through the registration process." },
    ],
  },

  // ─── TECH BUILD + AI ──────────────────────────────────────────────────────
  {
    slug: "ai-automation",
    category: "Tech Build + AI",
    categorySlug: "tech-build",
    name: "AI Automation",
    tagline: "Automate your repetitive tasks with AI-powered workflows",
    description:
      "We build intelligent automation workflows that connect your apps, eliminate manual tasks, and use AI to process, classify, and act on data. From WhatsApp auto-replies to CRM data pipelines — we automate what slows you down.",
    startingPrice: "Price on request",
    deliveryTime: "5–14 days",
    icon: "Zap",
    features: [
      "Workflow mapping and automation planning",
      "Tool integration: Make.com, n8n, Zapier",
      "WhatsApp Business automation",
      "Lead qualification and CRM sync",
      "AI-powered email routing and responses",
      "Data extraction and report automation",
      "Slack / Teams notification workflows",
      "Custom API integrations",
    ],
    process: [
      { step: "Audit", detail: "Map your current workflows and identify automation opportunities" },
      { step: "Plan", detail: "Design the automation blueprint" },
      { step: "Build", detail: "Implement using Make.com, n8n, or custom code" },
      { step: "Test", detail: "Full testing with real data before handover" },
      { step: "Handover", detail: "Documentation and training session" },
    ],
    faqs: [
      { q: "What tools do you use?", a: "Make.com (formerly Integromat), n8n, Zapier, and custom Python/Node.js scripts depending on complexity." },
      { q: "Can you automate WhatsApp?", a: "Yes — using WhatsApp Business API or tools like Wati and Respond.io." },
    ],
  },
  {
    slug: "mvp-development",
    category: "Tech Build + AI",
    categorySlug: "tech-build",
    name: "MVP Development",
    tagline: "Turn your idea into a working product — fast",
    description:
      "We build Minimum Viable Products for startups and founders who want to validate their idea with real users before investing in a full product. Lean, functional, and production-ready — in 6–10 weeks.",
    startingPrice: "Price on request",
    deliveryTime: "6–10 weeks",
    icon: "Rocket",
    features: [
      "Product discovery and scoping session",
      "UI/UX wireframes and clickable prototype",
      "Full-stack development (Next.js + Supabase)",
      "User authentication and role management",
      "Core feature set (defined in discovery)",
      "Mobile-responsive design",
      "Deployment on Vercel or your preferred host",
      "Source code handover",
      "30 days post-launch support",
    ],
    process: [
      { step: "Discovery", detail: "Define problem, users, core features, and success metrics" },
      { step: "Design", detail: "Wireframes and UI design in Figma" },
      { step: "Build", detail: "Iterative development sprints (2-week cycles)" },
      { step: "Test", detail: "Internal QA + beta user testing" },
      { step: "Launch", detail: "Deploy, monitor, and iterate" },
    ],
    faqs: [
      { q: "What's included in the MVP?", a: "We define the feature set together in discovery. Typically: auth, core user flow, dashboard, and basic admin." },
      { q: "What tech stack do you use?", a: "Next.js 15, TypeScript, Supabase, Tailwind CSS — modern, scalable, and easy to hand off." },
      { q: "Do I own the code?", a: "100% — you get the full source code and all assets." },
    ],
  },
  {
    slug: "saas-products",
    category: "Tech Build + AI",
    categorySlug: "tech-build",
    name: "Custom SaaS Development",
    tagline: "We build your SaaS product from idea to revenue",
    description:
      "We build production-grade SaaS applications with subscription billing, multi-tenant architecture, admin dashboards, and everything you need to go from idea to paying customers.",
    startingPrice: "Price on request",
    deliveryTime: "8–16 weeks",
    icon: "Layers",
    features: [
      "Full product discovery and architecture planning",
      "UI/UX design in Figma",
      "Multi-tenant SaaS architecture",
      "Subscription billing (Stripe)",
      "Role-based access control",
      "Admin dashboard and user management",
      "API design and documentation",
      "CI/CD pipeline setup",
      "Analytics and usage tracking",
      "6 months support option available",
    ],
    process: [
      { step: "Discovery", detail: "Deep-dive into your product vision, market, and users" },
      { step: "Architecture", detail: "Technical design, data model, API structure" },
      { step: "Design", detail: "Full UI/UX in Figma — all screens" },
      { step: "Development", detail: "Agile sprints with weekly demos" },
      { step: "Launch", detail: "Production deployment, monitoring, handover" },
    ],
    faqs: [
      { q: "What's the difference between MVP and SaaS build?", a: "An MVP is the fastest path to validation. A full SaaS build includes billing, multi-tenancy, admin tools, and production infrastructure." },
      { q: "Do you do ongoing maintenance?", a: "Yes — monthly retainer options available after launch." },
    ],
  },
];

export const serviceCategories = [
  {
    name: "Web Development",
    slug: "web-development",
    description: "Shopify, WooCommerce, and company websites built to convert",
    color: "violet",
    icon: "Globe",
    services: services.filter((s) => s.categorySlug === "web-development"),
  },
  {
    name: "Digital Marketing",
    slug: "digital-marketing",
    description: "Google, Meta, TikTok, LinkedIn ads + SEO",
    color: "teal",
    icon: "TrendingUp",
    services: services.filter((s) => s.categorySlug === "digital-marketing"),
  },
  {
    name: "Smart Tools",
    slug: "smart-tools",
    description: "NFC cards, QR codes, digital business cards, AI chatbots",
    color: "amber",
    icon: "Zap",
    services: services.filter((s) => s.categorySlug === "smart-tools"),
  },
  {
    name: "Marketplace Listings",
    slug: "marketplace-listings",
    description: "Amazon and Noon listing optimisation for the Middle East and beyond",
    color: "coral",
    icon: "ShoppingCart",
    services: services.filter((s) => s.categorySlug === "marketplace-listings"),
  },
  {
    name: "Tech Build + AI",
    slug: "tech-build",
    description: "AI automation, MVP development, and custom SaaS products",
    color: "blue",
    icon: "Cpu",
    services: services.filter((s) => s.categorySlug === "tech-build"),
  },
];
